[package]
name = "algorithms"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "217_contains_duplicate" 
path = "bin/217_contains_duplicate.rs" 

[[bin]]
name = "242_valid_anagram" 
path = "bin/242_valid_anagram.rs" 
